### ISSUE TITLE
Fix Homebrew upgrade

### ISSUE THREAD

**Issue by dubesoftware** [openresty/homebrew-brew#23]
### Indicate troubleshooting steps taken

I was upgrading my Homebrew formulae and got the following error trace:

```
Warning: Calling bottle :unneeded is deprecated! There is no replacement.
Please report this issue to the openresty/brew tap (not Homebrew/brew or Homebrew/core):
  /usr/local/Homebrew/Library/Taps/openresty/homebrew-brew/Formula/php-session-nginx-module.rb:8

Warning: Calling bottle :unneeded is deprecated! There is no replacement.
Please report this issue to the openresty/brew tap (not Homebrew/brew or Homebrew/core):
  /usr/local/Homebrew/Library/Taps/openresty/homebrew-brew/Formula/auth-ldap-nginx-module.rb:9

Warning: Calling bottle :unneeded is deprecated! There is no replacement.
Please report this issue to the openresty/brew tap (not Homebrew/brew or Homebrew/core):
  /usr/local/Homebrew/Library/Taps/openresty/homebrew-brew/Formula/extended-status-nginx-module.rb:7

Warning: Calling bottle :unneeded is deprecated! There is no replacement.
Please report this issue to the openresty/brew tap (not Homebrew/brew or Homebrew/core):
  /usr/local/Homebrew/Library/Taps/openresty/homebrew-brew/Formula/txid-nginx-module.rb:8

Warning: Calling bottle :unneeded is deprecated! There is no replacement.
Please report this issue to the openresty/brew tap (not Homebrew/brew or Homebrew/core):
  /usr/local/Homebrew/Library/Taps/openresty/homebrew-brew/Formula/notice-nginx-module.rb:8

Warning: Calling bottle :unneeded is deprecated! There is no replacement.
Please report this issue to the openresty/brew tap (not Homebrew/brew or Homebrew/core):
  /usr/local/Homebrew/Library/Taps/openresty/homebrew-brew/Formula/upload-nginx-module.rb:8

Warning: Calling bottle :unneeded is deprecated! There is no replacement.
Please report this issue to the openresty/brew tap (not Homebrew/brew or Homebrew/core):
  /usr/local/Homebrew/Library/Taps/openresty/homebrew-brew/Formula/mruby-nginx-module.rb:7

Warning: Calling bottle :unneeded is deprecated! There is no replacement.
Please report this issue to the openresty/brew tap (not Homebrew/brew or Homebrew/core):
  /usr/local/Homebrew/Library/Taps/openresty/homebrew-brew/Formula/lua-nginx-module.rb:8

Warning: Calling bottle :unneeded is deprecated! There is no replacement.
Please report this issue to the openresty/brew tap (not Homebrew/brew or Homebrew/core):
  /usr/local/Homebrew/Library/Taps/openresty/homebrew-brew/Formula/ctpp2-nginx-module.rb:8

Warning: Calling bottle :unneeded is deprecated! There is no replacement.
Please report this issue to the openresty/brew tap (not Homebrew/brew or Homebrew/core):
  /usr/local/Homebrew/Library/Taps/openresty/homebrew-brew/Formula/redis-nginx-module.rb:7

Warning: Calling bottle :unneeded is deprecated! There is no replacement.
Please report this issue to the openresty/brew tap (not Homebrew/brew or Homebrew/core):
  /usr/local/Homebrew/Library/Taps/openresty/homebrew-brew/Formula/mogilefs-nginx-module.rb:8

Warning: Calling bottle :unneeded is deprecated! There is no replacement.
Please report this issue to the openresty/brew tap (not Homebrew/brew or Homebrew/core):
  /usr/local/Homebrew/Library/Taps/openresty/homebrew-brew/Formula/nchan-nginx-module.rb:8

Warning: Calling bottle :unneeded is deprecated! There is no replacement.
Please report this issue to the openresty/brew tap (not Homebrew/brew or Homebrew/core):
  /usr/local/Homebrew/Library/Taps/openresty/homebrew-brew/Formula/cache-purge-nginx-module.rb:7

Warning: Calling bottle :unneeded is deprecated! There is no replacement.
Please report this issue to the openresty/brew tap (not Homebrew/brew or Homebrew/core):
  /usr/local/Homebrew/Library/Taps/openresty/homebrew-brew/Formula/dav-ext-nginx-module.rb:7

Warning: Calling bottle :unneeded is deprecated! There is no replacement.
Please report this issue to the openresty/brew tap (not Homebrew/brew or Homebrew/core):
  /usr/local/Homebrew/Library/Taps/openresty/homebrew-brew/Formula/accesskey-nginx-module.rb:7

Warning: Calling bottle :unneeded is deprecated! There is no replacement.
Please report this issue to the openresty/brew tap (not Homebrew/brew or Homebrew/core):
  /usr/local/Homebrew/Library/Taps/openresty/homebrew-brew/Formula/eval-nginx-module.rb:7

Warning: Calling bottle :unneeded is deprecated! There is no replacement.
Please report this issue to the openresty/brew tap (not Homebrew/brew or Homebrew/core):
  /usr/local/Homebrew/Library/Taps/openresty/homebrew-brew/Formula/anti-ddos-nginx-module.rb:8

Warning: Calling bottle :unneeded is deprecated! There is no replacement.
Please report this issue to the openresty/brew tap (not Homebrew/brew or Homebrew/core):
  /usr/local/Homebrew/Library/Taps/openresty/homebrew-brew/Formula/healthcheck-nginx-module.rb:8

Warning: Calling bottle :unneeded is deprecated! There is no replacement.
Please report this issue to the openresty/brew tap (not Homebrew/brew or Homebrew/core):
  /usr/local/Homebrew/Library/Taps/openresty/homebrew-brew/Formula/realtime-req-nginx-module.rb:7

Warning: Calling bottle :unneeded is deprecated! There is no replacement.
Please report this issue to the openresty/brew tap (not Homebrew/brew or Homebrew/core):
  /usr/local/Homebrew/Library/Taps/openresty/homebrew-brew/Formula/auth-digest-nginx-module.rb:9

Warning: Calling bottle :unneeded is deprecated! There is no replacement.
Please report this issue to the openresty/brew tap (not Homebrew/brew or Homebrew/core):
  /usr/local/Homebrew/Library/Taps/openresty/homebrew-brew/Formula/mod-zip-nginx-module.rb:8

Warning: Calling bottle :unneeded is deprecated! There is no replacement.
Please report this issue to the openresty/brew tap (not Homebrew/brew or Homebrew/core):
  /usr/local/Homebrew/Library/Taps/openresty/homebrew-brew/Formula/set-misc-nginx-module.rb:7

Warning: Calling bottle :unneeded is deprecated! There is no replacement.
Please report this issue to the openresty/brew tap (not Homebrew/brew or Homebrew/core):
  /usr/local/Homebrew/Library/Taps/openresty/homebrew-brew/Formula/dosdetector-nginx-module.rb:8

Warning: Calling bottle :unneeded is deprecated! There is no replacement.
Please report this issue to the openresty/brew tap (not Homebrew/brew or Homebrew/core):
  /usr/local/Homebrew/Library/Taps/openresty/homebrew-brew/Formula/auto-keepalive-nginx-module.rb:7

Warning: Calling bottle :unneeded is deprecated! There is no replacement.
Please report this issue to the openresty/brew tap (not Homebrew/brew or Homebrew/core):
  /usr/local/Homebrew/Library/Taps/openresty/homebrew-brew/Formula/ajp-nginx-module.rb:8

Warning: Calling bottle :unneeded is deprecated! There is no replacement.
Please report this issue to the openresty/brew tap (not Homebrew/brew or Homebrew/core):
  /usr/local/Homebrew/Library/Taps/openresty/homebrew-brew/Formula/geoip2-nginx-module.rb:7

Warning: Calling bottle :unneeded is deprecated! There is no replacement.
Please report this issue to the openresty/brew tap (not Homebrew/brew or Homebrew/core):
  /usr/local/Homebrew/Library/Taps/openresty/homebrew-brew/Formula/push-stream-nginx-module.rb:7

Warning: Calling bottle :unneeded is deprecated! There is no replacement.
Please report this issue to the openresty/brew tap (not Homebrew/brew or Homebrew/core):
  /usr/local/Homebrew/Library/Taps/openresty/homebrew-brew/Formula/ngx-devel-kit.rb:8

Warning: Calling bottle :unneeded is deprecated! There is no replacement.
Please report this issue to the openresty/brew tap (not Homebrew/brew or Homebrew/core):
  /usr/local/Homebrew/Library/Taps/openresty/homebrew-brew/Formula/auth-pam-nginx-module.rb:7

Warning: Calling bottle :unneeded is deprecated! There is no replacement.
Please report this issue to the openresty/brew tap (not Homebrew/brew or Homebrew/core):
  /usr/local/Homebrew/Library/Taps/openresty/homebrew-brew/Formula/counter-zone-nginx-module.rb:7

Warning: Calling bottle :unneeded is deprecated! There is no replacement.
Please report this issue to the openresty/brew tap (not Homebrew/brew or Homebrew/core):
  /usr/local/Homebrew/Library/Taps/openresty/homebrew-brew/Formula/redis2-nginx-module.rb:7

Warning: Calling bottle :unneeded is deprecated! There is no replacement.
Please report this issue to the openresty/brew tap (not Homebrew/brew or Homebrew/core):
  /usr/local/Homebrew/Library/Taps/openresty/homebrew-brew/Formula/tarantool-nginx-module.rb:8

Warning: Calling bottle :unneeded is deprecated! There is no replacement.
Please report this issue to the openresty/brew tap (not Homebrew/brew or Homebrew/core):
  /usr/local/Homebrew/Library/Taps/openresty/homebrew-brew/Formula/captcha-nginx-module.rb:8

Warning: Calling bottle :unneeded is deprecated! There is no replacement.
Please report this issue to the openresty/brew tap (not Homebrew/brew or Homebrew/core):
  /usr/local/Homebrew/Library/Taps/openresty/homebrew-brew/Formula/autols-nginx-module.rb:7

Warning: Calling bottle :unneeded is deprecated! There is no replacement.
Please report this issue to the openresty/brew tap (not Homebrew/brew or Homebrew/core):
  /usr/local/Homebrew/Library/Taps/openresty/homebrew-brew/Formula/array-var-nginx-module.rb:7

Warning: Calling bottle :unneeded is deprecated! There is no replacement.
Please report this issue to the openresty/brew tap (not Homebrew/brew or Homebrew/core):
  /usr/local/Homebrew/Library/Taps/openresty/homebrew-brew/Formula/var-req-speed-nginx-module.rb:8

Warning: Calling bottle :unneeded is deprecated! There is no replacement.
Please report this issue to the openresty/brew tap (not Homebrew/brew or Homebrew/core):
  /usr/local/Homebrew/Library/Taps/openresty/homebrew-brew/Formula/echo-nginx-module.rb:8

Warning: Calling bottle :unneeded is deprecated! There is no replacement.
Please report this issue to the openresty/brew tap (not Homebrew/brew or Homebrew/core):
  /usr/local/Homebrew/Library/Taps/openresty/homebrew-brew/Formula/upstream-order-nginx-module.rb:8

Warning: Calling bottle :unneeded is deprecated! There is no replacement.
Please report this issue to the openresty/brew tap (not Homebrew/brew or Homebrew/core):
  /usr/local/Homebrew/Library/Taps/openresty/homebrew-brew/Formula/accept-language-nginx-module.rb:7

Warning: Calling bottle :unneeded is deprecated! There is no replacement.
Please report this issue to the openresty/brew tap (not Homebrew/brew or Homebrew/core):
  /usr/local/Homebrew/Library/Taps/openresty/homebrew-brew/Formula/http-remote-passwd-nginx-module.rb:7

Warning: Calling bottle :unneeded is deprecated! There is no replacement.
Please report this issue to the openresty/brew tap (not Homebrew/brew or Homebrew/core):
  /usr/local/Homebrew/Library/Taps/openresty/homebrew-brew/Formula/http-accounting-nginx-module.rb:7

Warning: Calling bottle :unneeded is deprecated! There is no replacement.
Please report this issue to the openresty/brew tap (not Homebrew/brew or Homebrew/core):
  /usr/local/Homebrew/Library/Taps/openresty/homebrew-brew/Formula/fancyindex-nginx-module.rb:8

Warning: Calling bottle :unneeded is deprecated! There is no replacement.
Please report this issue to the openresty/brew tap (not Homebrew/brew or Homebrew/core):
  /usr/local/Homebrew/Library/Taps/openresty/homebrew-brew/Formula/tcp-proxy-nginx-module.rb:7

Warning: Calling bottle :unneeded is deprecated! There is no replacement.
Please report this issue to the openresty/brew tap (not Homebrew/brew or Homebrew/core):
  /usr/local/Homebrew/Library/Taps/openresty/homebrew-brew/Formula/log-if-nginx-module.rb:9

Warning: Calling bottle :unneeded is deprecated! There is no replacement.
Please report this issue to the openresty/brew tap (not Homebrew/brew or Homebrew/core):
  /usr/local/Homebrew/Library/Taps/openresty/homebrew-brew/Formula/vod-nginx-module.rb:7

Warning: Calling bottle :unneeded is deprecated! There is no replacement.
Please report this issue to the openresty/brew tap (not Homebrew/brew or Homebrew/core):
  /usr/local/Homebrew/Library/Taps/openresty/homebrew-brew/Formula/headers-more-nginx-module.rb:7

Warning: Calling bottle :unneeded is deprecated! There is no replacement.
Please report this issue to the openresty/brew tap (not Homebrew/brew or Homebrew/core):
  /usr/local/Homebrew/Library/Taps/openresty/homebrew-brew/Formula/rtmp-nginx-module.rb:14

Warning: Calling bottle :unneeded is deprecated! There is no replacement.
Please report this issue to the openresty/brew tap (not Homebrew/brew or Homebrew/core):
  /usr/local/Homebrew/Library/Taps/openresty/homebrew-brew/Formula/stream-lua-nginx-module.rb:10

Warning: Calling bottle :unneeded is deprecated! There is no replacement.
Please report this issue to the openresty/brew tap (not Homebrew/brew or Homebrew/core):
  /usr/local/Homebrew/Library/Taps/openresty/homebrew-brew/Formula/xsltproc-nginx-module.rb:7

Warning: Calling bottle :unneeded is deprecated! There is no replacement.
Please report this issue to the openresty/brew tap (not Homebrew/brew or Homebrew/core):
  /usr/local/Homebrew/Library/Taps/openresty/homebrew-brew/Formula/websockify-nginx-module.rb:7

Warning: Calling bottle :unneeded is deprecated! There is no replacement.
Please report this issue to the openresty/brew tap (not Homebrew/brew or Homebrew/core):
  /usr/local/Homebrew/Library/Taps/openresty/homebrew-brew/Formula/upload-progress-nginx-module.rb:8

Warning: Calling bottle :unneeded is deprecated! There is no replacement.
Please report this issue to the openresty/brew tap (not Homebrew/brew or Homebrew/core):
  /usr/local/Homebrew/Library/Taps/openresty/homebrew-brew/Formula/subs-filter-nginx-module.rb:8

Warning: Calling bottle :unneeded is deprecated! There is no replacement.
Please report this issue to the openresty/brew tap (not Homebrew/brew or Homebrew/core):
  /usr/local/Homebrew/Library/Taps/openresty/homebrew-brew/Formula/ustats-nginx-module.rb:8

Warning: Calling bottle :unneeded is deprecated! There is no replacement.
Please report this issue to the openresty/brew tap (not Homebrew/brew or Homebrew/core):
  /usr/local/Homebrew/Library/Taps/openresty/homebrew-brew/Formula/mp4-h264-nginx-module.rb:7

Warning: Calling bottle :unneeded is deprecated! There is no replacement.
Please report this issue to the openresty/brew tap (not Homebrew/brew or Homebrew/core):
  /usr/local/Homebrew/Library/Taps/openresty/homebrew-brew/Formula/unzip-nginx-module.rb:8

Warning: Calling bottle :unneeded is deprecated! There is no replacement.
Please report this issue to the openresty/brew tap (not Homebrew/brew or Homebrew/core):
  /usr/local/Homebrew/Library/Taps/openresty/homebrew-brew/Formula/http-flood-detector-nginx-module.rb:8

Warning: Calling bottle :unneeded is deprecated! There is no replacement.
Please report this issue to the openresty/brew tap (not Homebrew/brew or Homebrew/core):
  /usr/local/Homebrew/Library/Taps/openresty/homebrew-brew/Formula/small-light-nginx-module.rb:7

Warning: Calling bottle :unneeded is deprecated! There is no replacement.
Please report this issue to the openresty/brew tap (not Homebrew/brew or Homebrew/core):
  /usr/local/Homebrew/Library/Taps/openresty/homebrew-brew/Formula/naxsi-nginx-module.rb:9
```

When I run `brew info openresty`, I get the version number 1.19.9.1_2

My Homebrew version is 3.3.0.

**Comment by dubesoftware** [comment]
Does anyone know what needs to be done here?

**Comment by dubesoftware** [comment]
This issue appears resolved. I uninstalled, untapped and reinstalled OpenResty using Homebrew. Not sure if this solved the issue or if something was updated - I haven't checked (OpenResty is at stable 1.19.9.1).

**Comment by dubesoftware** [comment]
Well, when I run `brew update && brew upgrade` I still get the following output:

`Warning: Calling bottle :unneeded is deprecated! There is no replacement.
Please report this issue to the openresty/brew tap (not Homebrew/brew or Homebrew/core):
  /usr/local/Homebrew/Library/Taps/openresty/homebrew-brew/Formula/php-session-nginx-module.rb:8

Warning: Calling bottle :unneeded is deprecated! There is no replacement.
Please report this issue to the openresty/brew tap (not Homebrew/brew or Homebrew/core):
  /usr/local/Homebrew/Library/Taps/openresty/homebrew-brew/Formula/auth-ldap-nginx-module.rb:9

Warning: Calling bottle :unneeded is deprecated! There is no replacement.
Please report this issue to the openresty/brew tap (not Homebrew/brew or Homebrew/core):
  /usr/local/Homebrew/Library/Taps/openresty/homebrew-brew/Formula/extended-status-nginx-module.rb:7

Warning: Calling bottle :unneeded is deprecated! There is no replacement.
Please report this issue to the openresty/brew tap (not Homebrew/brew or Homebrew/core):
  /usr/local/Homebrew/Library/Taps/openresty/homebrew-brew/Formula/txid-nginx-module.rb:8

Warning: Calling bottle :unneeded is deprecated! There is no replacement.
Please report this issue to the openresty/brew tap (not Homebrew/brew or Homebrew/core):
  /usr/local/Homebrew/Library/Taps/openresty/homebrew-brew/Formula/notice-nginx-module.rb:8

Warning: Calling bottle :unneeded is deprecated! There is no replacement.
Please report this issue to the openresty/brew tap (not Homebrew/brew or Homebrew/core):
  /usr/local/Homebrew/Library/Taps/openresty/homebrew-brew/Formula/upload-nginx-module.rb:8

Warning: Calling bottle :unneeded is deprecated! There is no replacement.
Please report this issue to the openresty/brew tap (not Homebrew/brew or Homebrew/core):
  /usr/local/Homebrew/Library/Taps/openresty/homebrew-brew/Formula/mruby-nginx-module.rb:7

Warning: Calling bottle :unneeded is deprecated! There is no replacement.
Please report this issue to the openresty/brew tap (not Homebrew/brew or Homebrew/core):
  /usr/local/Homebrew/Library/Taps/openresty/homebrew-brew/Formula/lua-nginx-module.rb:8

Warning: Calling bottle :unneeded is deprecated! There is no replacement.
Please report this issue to the openresty/brew tap (not Homebrew/brew or Homebrew/core):
  /usr/local/Homebrew/Library/Taps/openresty/homebrew-brew/Formula/ctpp2-nginx-module.rb:8

Warning: Calling bottle :unneeded is deprecated! There is no replacement.
Please report this issue to the openresty/brew tap (not Homebrew/brew or Homebrew/core):
  /usr/local/Homebrew/Library/Taps/openresty/homebrew-brew/Formula/redis-nginx-module.rb:7

Warning: Calling bottle :unneeded is deprecated! There is no replacement.
Please report this issue to the openresty/brew tap (not Homebrew/brew or Homebrew/core):
  /usr/local/Homebrew/Library/Taps/openresty/homebrew-brew/Formula/mogilefs-nginx-module.rb:8

Warning: Calling bottle :unneeded is deprecated! There is no replacement.
Please report this issue to the openresty/brew tap (not Homebrew/brew or Homebrew/core):
  /usr/local/Homebrew/Library/Taps/openresty/homebrew-brew/Formula/nchan-nginx-module.rb:8

Warning: Calling bottle :unneeded is deprecated! There is no replacement.
Please report this issue to the openresty/brew tap (not Homebrew/brew or Homebrew/core):
  /usr/local/Homebrew/Library/Taps/openresty/homebrew-brew/Formula/cache-purge-nginx-module.rb:7

Warning: Calling bottle :unneeded is deprecated! There is no replacement.
Please report this issue to the openresty/brew tap (not Homebrew/brew or Homebrew/core):
  /usr/local/Homebrew/Library/Taps/openresty/homebrew-brew/Formula/dav-ext-nginx-module.rb:7

Warning: Calling bottle :unneeded is deprecated! There is no replacement.
Please report this issue to the openresty/brew tap (not Homebrew/brew or Homebrew/core):
  /usr/local/Homebrew/Library/Taps/openresty/homebrew-brew/Formula/accesskey-nginx-module.rb:7

Warning: Calling bottle :unneeded is deprecated! There is no replacement.
Please report this issue to the openresty/brew tap (not Homebrew/brew or Homebrew/core):
  /usr/local/Homebrew/Library/Taps/openresty/homebrew-brew/Formula/eval-nginx-module.rb:7

Warning: Calling bottle :unneeded is deprecated! There is no replacement.
Please report this issue to the openresty/brew tap (not Homebrew/brew or Homebrew/core):
  /usr/local/Homebrew/Library/Taps/openresty/homebrew-brew/Formula/anti-ddos-nginx-module.rb:8

Warning: Calling bottle :unneeded is deprecated! There is no replacement.
Please report this issue to the openresty/brew tap (not Homebrew/brew or Homebrew/core):
  /usr/local/Homebrew/Library/Taps/openresty/homebrew-brew/Formula/healthcheck-nginx-module.rb:8

Warning: Calling bottle :unneeded is deprecated! There is no replacement.
Please report this issue to the openresty/brew tap (not Homebrew/brew or Homebrew/core):
  /usr/local/Homebrew/Library/Taps/openresty/homebrew-brew/Formula/realtime-req-nginx-module.rb:7

Warning: Calling bottle :unneeded is deprecated! There is no replacement.
Please report this issue to the openresty/brew tap (not Homebrew/brew or Homebrew/core):
  /usr/local/Homebrew/Library/Taps/openresty/homebrew-brew/Formula/auth-digest-nginx-module.rb:9

Warning: Calling bottle :unneeded is deprecated! There is no replacement.
Please report this issue to the openresty/brew tap (not Homebrew/brew or Homebrew/core):
  /usr/local/Homebrew/Library/Taps/openresty/homebrew-brew/Formula/mod-zip-nginx-module.rb:8

Warning: Calling bottle :unneeded is deprecated! There is no replacement.
Please report this issue to the openresty/brew tap (not Homebrew/brew or Homebrew/core):
  /usr/local/Homebrew/Library/Taps/openresty/homebrew-brew/Formula/set-misc-nginx-module.rb:7

Warning: Calling bottle :unneeded is deprecated! There is no replacement.
Please report this issue to the openresty/brew tap (not Homebrew/brew or Homebrew/core):
  /usr/local/Homebrew/Library/Taps/openresty/homebrew-brew/Formula/dosdetector-nginx-module.rb:8

Warning: Calling bottle :unneeded is deprecated! There is no replacement.
Please report this issue to the openresty/brew tap (not Homebrew/brew or Homebrew/core):
  /usr/local/Homebrew/Library/Taps/openresty/homebrew-brew/Formula/auto-keepalive-nginx-module.rb:7

Warning: Calling bottle :unneeded is deprecated! There is no replacement.
Please report this issue to the openresty/brew tap (not Homebrew/brew or Homebrew/core):
  /usr/local/Homebrew/Library/Taps/openresty/homebrew-brew/Formula/ajp-nginx-module.rb:8

Warning: Calling bottle :unneeded is deprecated! There is no replacement.
Please report this issue to the openresty/brew tap (not Homebrew/brew or Homebrew/core):
  /usr/local/Homebrew/Library/Taps/openresty/homebrew-brew/Formula/geoip2-nginx-module.rb:7

Warning: Calling bottle :unneeded is deprecated! There is no replacement.
Please report this issue to the openresty/brew tap (not Homebrew/brew or Homebrew/core):
  /usr/local/Homebrew/Library/Taps/openresty/homebrew-brew/Formula/push-stream-nginx-module.rb:7

Warning: Calling bottle :unneeded is deprecated! There is no replacement.
Please report this issue to the openresty/brew tap (not Homebrew/brew or Homebrew/core):
  /usr/local/Homebrew/Library/Taps/openresty/homebrew-brew/Formula/ngx-devel-kit.rb:8

Warning: Calling bottle :unneeded is deprecated! There is no replacement.
Please report this issue to the openresty/brew tap (not Homebrew/brew or Homebrew/core):
  /usr/local/Homebrew/Library/Taps/openresty/homebrew-brew/Formula/auth-pam-nginx-module.rb:7

Warning: Calling bottle :unneeded is deprecated! There is no replacement.
Please report this issue to the openresty/brew tap (not Homebrew/brew or Homebrew/core):
  /usr/local/Homebrew/Library/Taps/openresty/homebrew-brew/Formula/counter-zone-nginx-module.rb:7

Warning: Calling bottle :unneeded is deprecated! There is no replacement.
Please report this issue to the openresty/brew tap (not Homebrew/brew or Homebrew/core):
  /usr/local/Homebrew/Library/Taps/openresty/homebrew-brew/Formula/redis2-nginx-module.rb:7

Warning: Calling bottle :unneeded is deprecated! There is no replacement.
Please report this issue to the openresty/brew tap (not Homebrew/brew or Homebrew/core):
  /usr/local/Homebrew/Library/Taps/openresty/homebrew-brew/Formula/tarantool-nginx-module.rb:8

Warning: Calling bottle :unneeded is deprecated! There is no replacement.
Please report this issue to the openresty/brew tap (not Homebrew/brew or Homebrew/core):
  /usr/local/Homebrew/Library/Taps/openresty/homebrew-brew/Formula/captcha-nginx-module.rb:8

Warning: Calling bottle :unneeded is deprecated! There is no replacement.
Please report this issue to the openresty/brew tap (not Homebrew/brew or Homebrew/core):
  /usr/local/Homebrew/Library/Taps/openresty/homebrew-brew/Formula/autols-nginx-module.rb:7

Warning: Calling bottle :unneeded is deprecated! There is no replacement.
Please report this issue to the openresty/brew tap (not Homebrew/brew or Homebrew/core):
  /usr/local/Homebrew/Library/Taps/openresty/homebrew-brew/Formula/array-var-nginx-module.rb:7

Warning: Calling bottle :unneeded is deprecated! There is no replacement.
Please report this issue to the openresty/brew tap (not Homebrew/brew or Homebrew/core):
  /usr/local/Homebrew/Library/Taps/openresty/homebrew-brew/Formula/var-req-speed-nginx-module.rb:8

Warning: Calling bottle :unneeded is deprecated! There is no replacement.
Please report this issue to the openresty/brew tap (not Homebrew/brew or Homebrew/core):
  /usr/local/Homebrew/Library/Taps/openresty/homebrew-brew/Formula/echo-nginx-module.rb:8

Warning: Calling bottle :unneeded is deprecated! There is no replacement.
Please report this issue to the openresty/brew tap (not Homebrew/brew or Homebrew/core):
  /usr/local/Homebrew/Library/Taps/openresty/homebrew-brew/Formula/upstream-order-nginx-module.rb:8

Warning: Calling bottle :unneeded is deprecated! There is no replacement.
Please report this issue to the openresty/brew tap (not Homebrew/brew or Homebrew/core):
  /usr/local/Homebrew/Library/Taps/openresty/homebrew-brew/Formula/accept-language-nginx-module.rb:7

Warning: Calling bottle :unneeded is deprecated! There is no replacement.
Please report this issue to the openresty/brew tap (not Homebrew/brew or Homebrew/core):
  /usr/local/Homebrew/Library/Taps/openresty/homebrew-brew/Formula/http-remote-passwd-nginx-module.rb:7

Warning: Calling bottle :unneeded is deprecated! There is no replacement.
Please report this issue to the openresty/brew tap (not Homebrew/brew or Homebrew/core):
  /usr/local/Homebrew/Library/Taps/openresty/homebrew-brew/Formula/http-accounting-nginx-module.rb:7

Warning: Calling bottle :unneeded is deprecated! There is no replacement.
Please report this issue to the openresty/brew tap (not Homebrew/brew or Homebrew/core):
  /usr/local/Homebrew/Library/Taps/openresty/homebrew-brew/Formula/fancyindex-nginx-module.rb:8

Warning: Calling bottle :unneeded is deprecated! There is no replacement.
Please report this issue to the openresty/brew tap (not Homebrew/brew or Homebrew/core):
  /usr/local/Homebrew/Library/Taps/openresty/homebrew-brew/Formula/tcp-proxy-nginx-module.rb:7

Warning: Calling bottle :unneeded is deprecated! There is no replacement.
Please report this issue to the openresty/brew tap (not Homebrew/brew or Homebrew/core):
  /usr/local/Homebrew/Library/Taps/openresty/homebrew-brew/Formula/log-if-nginx-module.rb:9

Warning: Calling bottle :unneeded is deprecated! There is no replacement.
Please report this issue to the openresty/brew tap (not Homebrew/brew or Homebrew/core):
  /usr/local/Homebrew/Library/Taps/openresty/homebrew-brew/Formula/vod-nginx-module.rb:7

Warning: Calling bottle :unneeded is deprecated! There is no replacement.
Please report this issue to the openresty/brew tap (not Homebrew/brew or Homebrew/core):
  /usr/local/Homebrew/Library/Taps/openresty/homebrew-brew/Formula/headers-more-nginx-module.rb:7

Warning: Calling bottle :unneeded is deprecated! There is no replacement.
Please report this issue to the openresty/brew tap (not Homebrew/brew or Homebrew/core):
  /usr/local/Homebrew/Library/Taps/openresty/homebrew-brew/Formula/rtmp-nginx-module.rb:14

Warning: Calling bottle :unneeded is deprecated! There is no replacement.
Please report this issue to the openresty/brew tap (not Homebrew/brew or Homebrew/core):
  /usr/local/Homebrew/Library/Taps/openresty/homebrew-brew/Formula/stream-lua-nginx-module.rb:10

Warning: Calling bottle :unneeded is deprecated! There is no replacement.
Please report this issue to the openresty/brew tap (not Homebrew/brew or Homebrew/core):
  /usr/local/Homebrew/Library/Taps/openresty/homebrew-brew/Formula/xsltproc-nginx-module.rb:7

Warning: Calling bottle :unneeded is deprecated! There is no replacement.
Please report this issue to the openresty/brew tap (not Homebrew/brew or Homebrew/core):
  /usr/local/Homebrew/Library/Taps/openresty/homebrew-brew/Formula/websockify-nginx-module.rb:7

Warning: Calling bottle :unneeded is deprecated! There is no replacement.
Please report this issue to the openresty/brew tap (not Homebrew/brew or Homebrew/core):
  /usr/local/Homebrew/Library/Taps/openresty/homebrew-brew/Formula/upload-progress-nginx-module.rb:8

Warning: Calling bottle :unneeded is deprecated! There is no replacement.
Please report this issue to the openresty/brew tap (not Homebrew/brew or Homebrew/core):
  /usr/local/Homebrew/Library/Taps/openresty/homebrew-brew/Formula/subs-filter-nginx-module.rb:8

Warning: Calling bottle :unneeded is deprecated! There is no replacement.
Please report this issue to the openresty/brew tap (not Homebrew/brew or Homebrew/core):
  /usr/local/Homebrew/Library/Taps/openresty/homebrew-brew/Formula/ustats-nginx-module.rb:8

Warning: Calling bottle :unneeded is deprecated! There is no replacement.
Please report this issue to the openresty/brew tap (not Homebrew/brew or Homebrew/core):
  /usr/local/Homebrew/Library/Taps/openresty/homebrew-brew/Formula/mp4-h264-nginx-module.rb:7

Warning: Calling bottle :unneeded is deprecated! There is no replacement.
Please report this issue to the openresty/brew tap (not Homebrew/brew or Homebrew/core):
  /usr/local/Homebrew/Library/Taps/openresty/homebrew-brew/Formula/unzip-nginx-module.rb:8

Warning: Calling bottle :unneeded is deprecated! There is no replacement.
Please report this issue to the openresty/brew tap (not Homebrew/brew or Homebrew/core):
  /usr/local/Homebrew/Library/Taps/openresty/homebrew-brew/Formula/http-flood-detector-nginx-module.rb:8

Warning: Calling bottle :unneeded is deprecated! There is no replacement.
Please report this issue to the openresty/brew tap (not Homebrew/brew or Homebrew/core):
  /usr/local/Homebrew/Library/Taps/openresty/homebrew-brew/Formula/small-light-nginx-module.rb:7

Warning: Calling bottle :unneeded is deprecated! There is no replacement.
Please report this issue to the openresty/brew tap (not Homebrew/brew or Homebrew/core):
  /usr/local/Homebrew/Library/Taps/openresty/homebrew-brew/Formula/naxsi-nginx-module.rb:9`
 
What needs to be done to resolve this? I have capacity.

**Comment by dubesoftware** [comment]
Issue reopened.

**Comment by liwmj** [comment]
I also encountered the same problem, continue to pay attention, mark.

**Comment by dubesoftware** [comment]
I created a PR to resolve this (#24).

**Comment by spacewander** [comment]
@dubesoftware 
Thanks for your fix!
