### ISSUE TITLE
brew installation error

### ISSUE THREAD

**Issue by 0daypwn** [openresty/homebrew-brew#28]
Warning: Calling plist_options is deprecated! Use service.require_root instead.
Please report this issue to the openresty/brew tap (not Homebrew/brew or Homebrew/homebrew-core), or even better, submit a PR to fix it:
  /opt/homebrew/Library/Taps/openresty/homebrew-brew/Formula/openresty.rb:80

https://github.com/openresty/homebrew-brew/blob/99ef8e51aab7a5f9095f28086a70f258575e7e1e/Formula/openresty.rb#L80

**Comment by xiaocang** [comment]
This is a duplicate issue https://github.com/openresty/homebrew-brew/pull/29, and it's already fixed by https://github.com/openresty/homebrew-brew/pull/29 and https://github.com/openresty/homebrew-brew/pull/33
