### ISSUE TITLE
Brew warning:   "openresty: undefined method `require_root' for nil:NilClass"

### ISSUE THREAD

**Issue by dubesoftware** [openresty/homebrew-brew#32]
### Indicate troubleshooting steps taken

Yesterday while updating Brew formulae, Brew was giving the warning that the `plist_options` method was deprecated and advised to call `service.require_root` instead. I checked that fix in under PR #29 .

Today, Brew says:

> Warning: Some installed formulae are not readable: openresty: undefined method require_root for nil:NilClass.

The docs (https://rubydoc.brew.sh/Homebrew/Service.html#require_root-instance_method) say the Service class is defined in `service.rb`, which I have been unable to locate in the source.

Any ideas for resolving this?

**Comment by xiaocang** [comment]
already fixed by https://github.com/openresty/homebrew-brew/pull/33
